### ISSUE TITLE
Problem creating postgres DB with heifen sign.

### ISSUE THREAD

**Issue by alexvelea** [mciucu/manage-stem-app#1]
This happens when the folder has a heifen inside, and the DB-name is the project name (with heifen)

```
Traceback (most recent call last):
  File "/usr/bin/stem-app", line 72, in <module>
    sys.exit(main())
  File "/usr/bin/stem-app", line 52, in main
    SetupStemAppCommand(args.setup).run()
  File "/home/velea/work/manage-stem-app/commands/setup.py", line 71, in run
    self.ensure_database(database_name)
  File "/home/velea/work/manage-stem-app/commands/setup.py", line 41, in ensure_database
    database_cursor.execute("CREATE DATABASE " + database_name + ";")
psycopg2.ProgrammingError: syntax error at or near "-"
LINE 1: CREATE DATABASE site-velea;
```

**Comment by mciucu** [comment]
The project name is automatically transformed to lowercase and all non-alphanumberic characters (except `_`) are remove from the name when generating directory names and DB table names.
